subsystem:
	$(MAKE) -C Anasazi_Block_Davidson
	$(MAKE) -C Anasazi_Block_KrylovSchur 
	$(MAKE) -C Anasazi_LOBPCG 
	$(MAKE) -C Epetra_Power_Method 
	$(MAKE) -C Epetra_Simple_Vector 
	$(MAKE) -C Galeri_Linear_System 
	$(MAKE) -C Ifpack_Preconditioner_Factory 
	$(MAKE) -C Linear_Solver_Belos 
	$(MAKE) -C Linear_Solver_Ifpack 
	$(MAKE) -C Linear_Solver_ml 
	$(MAKE) -C Linear_Solver_mlMultiGrid 
	$(MAKE) -C NOX_Newton1 
	$(MAKE) -C NOX_Newton2 
	$(MAKE) -C Teuchos_BLAS
	$(MAKE) -C Teuchos_CLP 
	$(MAKE) -C Teuchos_LAPACK 
	$(MAKE) -C Teuchos_PL  
	$(MAKE) -C Teuchos_RCP 
	$(MAKE) -C Teuchos_SDM 
	$(MAKE) -C Teuchos_Time 
	$(MAKE) -C Tpetra_Init 
	$(MAKE) -C Tpetra_Vector 

